import { useCallback, useEffect, useState } from "react";
import { useAuth } from "../../../auth/useAuth.js";
import { Button, Card, ErrorState, Input, LoadingState, useToast } from "../../../components/ui/index.js";
import { PageHeader, StatusBadge } from "../../../components/data-display/index.js";
import { useCommunityResource } from "../hooks/useCommunityResource.js";
import { communityAdminService } from "../services/communityAdminService.js";

export function ProfilePage() {
  const { user, refreshUser } = useAuth(); const { showToast } = useToast(); const loader = useCallback(() => communityAdminService.getUser(user.id), [user.id]); const { data, loading, error, reload } = useCommunityResource(loader); const [form, setForm] = useState({ name: "", email: "", phone: "", password: "" }); const [saving, setSaving] = useState(false);
  useEffect(() => { if (data) setForm({ name: data.name || "", email: data.email || "", phone: data.phone || "", password: "" }); }, [data]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const payload = { name: form.name.trim(), email: form.email.trim().toLowerCase(), phone: form.phone.trim() }; if (form.password) payload.password = form.password; await communityAdminService.updateUser(user.id, payload); await refreshUser(); await reload(); showToast({ type: "success", message: "Profile updated." }); } catch (requestError) { showToast({ type: "error", message: requestError.message }); } finally { setSaving(false); } };
  return <><PageHeader eyebrow="Account" title="My profile" description="Update the contact and password fields supported by the user API." />{loading && <LoadingState message="Loading profile..." />}{error && <ErrorState message={error.message} onRetry={reload} />}{data && <div className="ca-grid ca-grid--2"><Card title="Account details"><dl className="ca-details"><div><dt>Role</dt><dd><StatusBadge status={data.role} label="Community Admin" /></dd></div><div><dt>User ID</dt><dd>{data.id}</dd></div><div><dt>Community ID</dt><dd>{data.communityId}</dd></div></dl></Card><Card title="Contact information"><form className="ca-form" onSubmit={submit}><Input label="Name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /><Input label="Email" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /><Input label="Phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /><Input label="New password" hint="Leave blank to keep the current password." type="password" minLength="8" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /><Button type="submit" loading={saving}>Save profile</Button></form></Card></div>}</>;
}
