export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  COMMUNITY_ADMIN: "COMMUNITY_ADMIN",
  TOWER_REPRESENTATIVE: "TOWER_REPRESENTATIVE",
  RESIDENT: "RESIDENT",
  MAINTENANCE_WORKER: "MAINTENANCE_WORKER",
});
