export const ROUTES = Object.freeze({
  HOME: "/",
  LOGIN: "/login",
  UNAUTHORIZED: "/unauthorized",
  SUPER_ADMIN: "/super-admin",
  SUPER_ADMIN_COMMUNITIES: "/super-admin/communities",
  SUPER_ADMIN_USERS: "/super-admin/users",
  SUPER_ADMIN_WORKFORCE: "/super-admin/workforce",
  SUPER_ADMIN_COMPLAINTS: "/super-admin/complaints",
  SUPER_ADMIN_REPORTS: "/super-admin/reports",
  SUPER_ADMIN_PROFILE: "/super-admin/profile",
  COMMUNITY_ADMIN: "/community-admin",
  COMMUNITY_ADMIN_COMPLAINTS: "/community-admin/complaints",
  COMMUNITY_ADMIN_HIERARCHY: "/community-admin/hierarchy",
  COMMUNITY_ADMIN_USERS: "/community-admin/users",
  COMMUNITY_ADMIN_WORKFORCE: "/community-admin/workforce",
  COMMUNITY_ADMIN_SUBSCRIPTION: "/community-admin/subscription",
  COMMUNITY_ADMIN_REPORTS: "/community-admin/reports",
  COMMUNITY_ADMIN_PROFILE: "/community-admin/profile",
  TOWER_REPRESENTATIVE: "/tower-representative",
  RESIDENT: "/resident",
  MAINTENANCE_WORKER: "/maintenance-worker",
});
