const workerState={page:"dashboard",profile:null,complaints:[],active:null};
const api=(p,o)=>window.UrbanityApi.apiRequest(p,o); const label=v=>String(v||"").toLowerCase().replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase()); const alertError=e=>window.alert(e.message||"Request failed.");
async function loadWorker(){const[p,c]=await Promise.all([api("/workforce/workers/me"),api("/complaints")]);workerState.profile=p.data;workerState.complaints=c.data||[];const u=window.UrbanityApi.getStoredUser()||{};document.querySelector(".profile-btn-name").textContent=u.email||"Maintenance Worker";}
function rows(items){return items.length?`<table class="tasks-table"><thead><tr><th>Maintenance Work</th><th>Status</th><th>Work Type</th></tr></thead><tbody>${items.map(c=>`<tr><td><button class="task" data-id="${c.id}">${c.title}</button></td><td>${label(c.status)}</td><td>${label(c.requiredWorkType)}</td></tr>`).join("")}</tbody></table>`:"<p>No assigned maintenance work.</p>"}
function dashboard(){const c=workerState.complaints,p=workerState.profile;return `<div class="page-header"><h1>Maintenance Worker Dashboard</h1></div><div class="stats-grid"><div class="stat-card"><b>${c.length}</b><span>Assigned work</span></div><div class="stat-card"><b>${c.filter(x=>x.status==="IN_PROGRESS").length}</b><span>In progress</span></div><div class="stat-card"><b>${p?.completedWorkCount||0}</b><span>Completed</span></div><div class="stat-card"><b>${p?.rating||0}</b><span>Rating</span></div></div><section class="content-card">${rows(c)}</section>`}
function profile(){const p=workerState.profile||{};return `<section class="content-card"><h1>Maintenance Worker Profile</h1><p><b>Specialization:</b> ${label(p.specialization)}<br><b>Work Status:</b> ${label(p.status)}<br><b>Rating:</b> ${p.rating||0}/5<br><b>Completed Work:</b> ${p.completedWorkCount||0}</p><h3>Work History</h3><p>${(p.workHistory||[]).join(", ")||"No completed work yet."}</p></section>`}
function render(page=workerState.page){workerState.page=page;let c=workerState.complaints;if(page==="in-progress")c=c.filter(x=>x.status==="IN_PROGRESS");if(page==="completed")c=c.filter(x=>["RESOLVED","REVIEWED","CLOSED"].includes(x.status));document.getElementById("pageContent").innerHTML=page==="dashboard"?dashboard():page==="profile"?profile():`<section class="content-card"><h1>Assigned Maintenance Work</h1>${rows(c)}</section>`;document.querySelectorAll(".nav-item").forEach(a=>a.classList.toggle("active",a.dataset.page===page));document.querySelectorAll(".task").forEach(b=>b.onclick=()=>openTask(b.dataset.id));}
async function openTask(id){try{const[c,a]=await Promise.all([api(`/complaints/${id}`),api(`/complaints/${id}/attachments`)]);workerState.active={...c.data,attachments:a.data||[]};const x=workerState.active;document.getElementById("modalContent").innerHTML=`<h3>${x.title}</h3><p>${x.description}</p><p><b>Type:</b> ${label(x.type)}<br><b>Work:</b> ${label(x.requiredWorkType)}<br><b>Status:</b> ${label(x.status)}</p><p><b>Attachments:</b> ${x.attachments.map(a=>a.originalName).join(", ")||"None"}</p>`;const b=document.getElementById("modalActionBtn");b.style.display=["ASSIGNED","IN_PROGRESS"].includes(x.status)?"inline-block":"none";b.textContent=x.status==="ASSIGNED"?"Start Work":"Resolve Work";b.onclick=()=>workerAction(x.id,x.status==="ASSIGNED"?"start":"resolve");document.getElementById("modalOverlay").classList.add("active");}catch(e){alertError(e)}}
async function workerAction(id,action){try{await api(`/complaints/${id}/${action}`,{method:"PATCH",body:{}});await loadWorker();document.getElementById("modalOverlay").classList.remove("active");render();}catch(e){alertError(e)}} function closeModal(){document.getElementById("modalOverlay").classList.remove("active");} function toggleDropdown(){document.getElementById("dropdownMenu").classList.toggle("show");}
document.addEventListener("DOMContentLoaded",async()=>{if(!window.UrbanityApi?.getAccessToken())return window.UrbanityApi?.logout();document.querySelectorAll(".nav-item").forEach(a=>a.onclick=e=>{e.preventDefault();render(a.dataset.page)});document.querySelectorAll(".signout-btn,.dropdown-signout").forEach(b=>b.onclick=()=>window.UrbanityApi.logout());try{await loadWorker();render()}catch(e){alertError(e)}});
